### ISSUE TITLE
Playback data - which format?

### ISSUE THREAD

**Issue by huguettecl** [AntoineBellemare/MEME#5]
Hi,

I'm trying to use your devices and I do not own a Muse headset. What is the required data format for EEG_playback? Do you know where I can find an existing dataset?

Also, is it possible to use your devices with other EEG headsets than MUSE ?

Thank you.

**Comment by huguettecl** [comment]
Thank you for adding some data! I managed to load it and play it with Playback but I cannot access it in other devices. How can I send Playback data to other modules like Mapper?

Thx

**Comment by huguettecl** [comment]
For example, I cannot see anything happening in EEG_viz or EEG_monitor. Can you?

**Comment by AntoineBellemare** [comment]
I added some data examples, which are the osc messages written in a .txt file.
I also added instruction in the readme on how to use it.
